server:
  port: 8088
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      discovery:
        locator:
           # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: test
          uri: lb://eureka-provider
          predicates:
            - Path=/hello
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/