server:
  port: 3404
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:3000/eureka/
  instance:
    preferIpAddress: true
spring:
  application:
    name: eureka-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gssun/springcloud #配置文件所在仓库
          username: gssun
          password: test 
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
